### ISSUE TITLE
EPIC -  Istio tests

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-gateway-api#23]
Issues for adding/fixing Istio conformance and e2e tests.
---

## Istio specific:

- [x] Add TestIngressTLS - https://github.com/istio/istio/issues/31747
- [x] Add TestVisibility* - https://github.com/istio/istio/issues/31746
- [x] Add TestRewriteHost - https://github.com/istio/istio/issues/31844

## Istio & gateway-api:
Note: as these tests get successfully run, their corresponding features get dropped from the list of [unavailable features](https://github.com/knative-sandbox/net-gateway-api/blob/main/docs/test-version.md).

- [x] [Fix 0 weight](https://github.com/knative-sandbox/net-ingressv2/blob/3ab8dafae86a18656f2861b2f30360930f2c1ecc/test/conformance/ingressv2/percentage.go#L125-L126) in TestPercentage - https://github.com/istio/istio/issues/31745, https://github.com/kubernetes-sigs/gateway-api/issues/596
- [ ] Add TestRetry - https://github.com/knative-sandbox/net-ingressv2/issues/20

**Comment by carlisia** [comment]
/lifecycle/active
