### ISSUE TITLE
EPIC - Contour tests

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-gateway-api#36]
Issues for adding/fixing Contour conformance and e2e tests.
---

## Critical issue:

- [x]  Multiple HTTPRoutes causes 404 https://github.com/projectcontour/contour/issues/3591

## Contour & gateway-api:
Note: as these tests get successfully run, their corresponding features get dropped from the list of [unavailable features](https://github.com/knative-sandbox/net-gateway-api/blob/main/docs/test-version.md).

- [ ] Add TestBasicsHTTP2 & TestGRPC/* https://github.com/kubernetes-sigs/gateway-api/issues/204
- [ ] Add TestIngressTLS
	- test should pass based on [Add support for TLS (conformance test passes) by evankanderson · Pull Request #316 · knative-sandbox/net-gateway-api](https://github.com/knative-sandbox/net-gateway-api/pull/316?w=1), but still need to be implemented.
	- https://github.com/projectcontour/contour/issues/3404
		- see: https://github.com/knative-sandbox/net-gateway-api/issues/36#issuecomment-889077033
- [ ] Add TestRetry - https://github.com/knative-sandbox/net-ingressv2/issues/20
- [ ] Add TestWebsocket https://github.com/kubernetes-sigs/gateway-api/issues/205

### Done
- [x] Add headers/* & dispatch/* https://github.com/projectcontour/contour/pull/3539 & https://github.com/projectcontour/contour/pull/3538
- [x] Add TestVisibility* 
- [x] Add TestPercentage - https://github.com/projectcontour/contour/issues/3560

**Comment by nak3** [comment]
Just note, Contour will change the design as https://github.com/projectcontour/contour/pull/3875 so it might effect on the status.
The current test is broken due to it.
